config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :sessions, only: [:create, :new, :destroy]
  resources :chats do
    resources :messages
  end
  resources :users

  # root 'notifications#index'
  root 'welcome#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :receiver_id, class_name: 'User'
  has_many :messages, dependent: :destroy


  validates_uniqueness_of :sender_id, scope: :receiver_id
  # validates_uniqueness_of :receiver_id, scope: :sender_id


  # checks whether a conversation exists between these two ids because we only want two users to have one conversation.
  scope :between, -> (sender_id,receiver_id) do
    where("(chats.sender_id = ? AND chats.receiver_id = ?) OR (chats.sender_id = ? AND chats.receiver_id =?)", sender_id, receiver_id, receiver_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :receiver_id, class_name: 'User'
  has_many :notifications, dependent: :destroy

  validates_presence_of :body, :chat_id, :sender_id, :receiver_id

  after_create_commit {MessageBroadcastJob.perform_now self}
  after_create_commit { notify }
  # after_create_commit if message is sent and not from current user = true/false

   def message_time
    time = created_at
    time.in_time_zone('Eastern Time (US & Canada)').strftime ("%m/%d/%y at %l:%M %p")
    # eventually change this method to get geolocator of the user and adjust to their time zone
   end

  private

  def notify
    Notification.create(event: "#{self.body}", message_id: self.id)
  end


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :message
  
  validates_presence_of :event, :message_id

  after_create_commit { NotificationBroadcastJob.perform_now(Notification.count,self, Message.last)}

end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, :last_name, :username, :email,  presence: true
  validates :email, :username, uniqueness: true
  validates :first_name, :last_name, length: { minimum: 2 }

  has_secure_password

  has_many :chats, dependent: :destroy, foreign_key: :sender_id
  has_many :messages, dependent: :destroy, foreign_key: :sender_id

  def self.authenticate!(email, password)
      user = self.find_by(:email => email)
      user.authenticate(password) if user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :notifications, if: :logged_in?
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end


  def notifications
    # sql = "SELECT * FROM notifications INNER JOIN messages ON notifications.message_id = messages.id INNER JOIN chats ON chats.id = messages.chat_id WHERE chats.receiver_id = #{current_user.id} OR chats.sender_id = #{current_user.id}"
    sql = "SELECT * FROM notifications INNER JOIN messages ON messages.id = notifications.message_id WHERE messages.receiver_id = #{current_user.id}"
    @notifications = Notification.find_by_sql(sql)

  end

  private
  def authenticate
    redirect_to root_path unless current_user
  end


  # Redirecting sign_up path on devise
  def after_sign_in_path_for(resource_or_scope)
    chats_path
  end

  def after_update_path_for(resource)
   chats_path
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate
  before_action :set_chat, only: [:update, :destroy, :show]

  def index
    @users = User.all
    @chats = Chat.all
  end

  def create

      if Chat.between(params[:sender_id], params[:receiver_id]).present?
        @chat = Chat.between(params[:sender_id], params[:receiver_id]).first
      else
        @chat = Chat.create(chat_params)
      end
    redirect_to chat_messages_path(@chat)
  end

  def update
  end

  def show
  end

  def destroy
    if @chat.present?
      @chat.destroy
    end
    redirect_to user_path(current_user)
  end

  private
  def set_chat
    @chat = Chat.find(params[:id])
  end

  def chat_params
    params.permit(:sender_id, :receiver_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate
  before_action :set_chat


  def index
    @messages = @chat.messages
    @message = @chat.messages.new
  end

  def new
    @message = @chat.messages.new
  end

  def create
    message = @chat.messages.new(message_params)
    if message.save
      ActionCable.server.broadcast 'messages',
       message: message.body
       head :ok
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :user_id, :sender_id, :receiver_id)
  end

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :login_required, only: [:new, :create, :destroy]

  def new
      @user = User.new
  end

  def create
      user = User.authenticate!(params[:user][:email], params[:user][:password])
      if user
        session[:user_id] = user.id
        redirect_to chats_path
      else
        flash[:error] = "Bad E-mail or Password"
        redirect_to login_path
      end
    end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def login(user)
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only:[:show, :destroy]
  before_action :set_user, only:[:edit, :update, :destroy]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to chats_path
    else
      render :new
    end
  end

  def show
    @chats = Chat.all
    @users = User.all
  end


  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user.destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/index.html.erb
    <div class="row align-center">
      <div class="col-sm-6 col-sm-offset-3 " id="chats">
        <h3 class="font-alt m-t-40 m-b-0">All Users</h3>
        <div class="ui list">
          <% @users.each do |user| %>
          <% if user.id != current_user.id %>
          <div class="item font-inc">
            <%= link_to user.username, chats_path(sender_id: current_user.id, receiver_id: user.id), method: 'post'%>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>

    </div>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">

    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand"%>
      </div>

      <div class="collapse navbar-collapse" id="custom-collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "All Users", chats_path%></li>
            <li><%= link_to "Inbox", user_path(current_user)%></li>
            <%= render "notifications/notification_center", notifications: @notifications %>
            <li><%= link_to 'Edit profile', edit_user_path(current_user), :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", logout_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
            <li><%= link_to "Sign up", signup_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", login_path, :class => 'navbar-link'  %></li>
        <% end %>
        </ul>
      </div>

    </div>

</nav>
<!-- /NAVIGATION -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>ActionCable Messenger by Cindy Kim</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
  <% if message.body %>
    <% user = User.find(message.user_id) %>
      <div class="header" id='msg<%=message.id%>' >
        <strong><%= user.username %></strong> <%= message.message_time %>
        <%= message.body %>
      </div>
  <% end %>

app/views/messages/index.html.erb
<section class="module">
  <div class="container" id="messages">
    <div class="form-group col-lg-12">
      <div class='messages' id="chat-box" style="overflow-y: scroll; height:400px;">
        <% @messages.each do |message| %>
          <% if message.body %>
            <% user = User.find(message.user_id) %>
              <div class="header">
                <strong><%= user.username %></strong> <%= message.message_time %>
                <%= message.body %>
              </div>
          <% end %>
        <% end %>
        <div data-chat=<%=@chat.id%>>
        </div>
        </div>
      </div>
    </div>




  <hr>
  <div class="container">
    <%= form_for [@chat, @message], url: chat_messages_path do |f| %>
    <div class="field" id='message_body'>
      <%= f.label :Message %> (Press Enter)<br>
      <%= f.text_area :body, class: "form-control", id: "body_message"%>
    </div>

    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>


    <% end %>

  </div>

</section>

app/views/notifications/_counter.html.erb
<li>
  <%= image_tag("bell.svg") %>
  <span  id="notification-counter"><%= counter %></span>
</li>

app/views/notifications/_notification.html.erb
<li>
  <%= notification.message.receiver.username %>
  <%= notification.event %>
  <span> <%= notification.created_at.in_time_zone('Eastern Time (US & Canada)').strftime ("%m/%d/%y at %l:%M %p") %></span>
</li>

app/views/notifications/_notification_center.html.erb
<ul class="notificator row">
  <a href="#" id="open_notification">
    <%= render 'notifications/counter', counter: notifications.count %>
  </a>
  <div id="notificationContainer">
    <div id="notificationTitle">Notifications</div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%= render partial: 'notifications/notification', collection: notifications%>
      </ul>
    </div>
    <div id="notificationFooter"></div>
  </div>
</ul>

app/views/users/edit.html.erb
<section class="module">
  <div class="container">
    <div class="form-group col-sm-4 col-sm-offset-4">
      <h2 class="module-title align-center font-alt">Edit <%= current_user.first_name %></h2>


      <div class="align-right">
        <%= link_to "Cancel", :back %>
      </div>
      <br>

      <%= form_for @user do |f| %>

      <div class="form-group">
        <%= f.text_field :first_name, class:"form-control", placeholder: "First Name", autofocus: true%>
      </div>

      <div class="form-group">
        <%= f.text_field :last_name, class:"form-control", placeholder: "Last Name", autofocus: true%>
      </div>

      <div class="form-group">
        <%= f.text_field :username, class:"form-control", placeholder: "User Name", autofocus: true%>
      </div>

      <div class="form-group">
        <%= f.email_field :email, class:"form-control", placeholder: "E-mail", autofocus: true%>
      </div>


      <div class="submit align-center">
  			<br>
  			<button type="submit" class="btn btn-d btn-round btn-sm">Update</button>
  		</div>
      <% end %>
      <br>
      <br>
      <br>

      <div class="submit align-center">
        <%= button_to "Delete Account", user_path, method: :delete, class: 'btn btn-danger btn-round'  %>
  		</div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="module">
  <div class="container">
    <div class="form-group col-sm-4 col-sm-offset-4">
      <h2 class="module-title align-center font-alt">Sign up</h2>

      <%= form_for @user, url: signup_path do |f| %>

      <div class="form-group">
        <%= f.text_field :first_name, class:"form-control", placeholder: "First Name", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.text_field :last_name, class:"form-control", placeholder: "Last Name", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :username, class:"form-control", placeholder: "User Name", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.email_field :email, class:"form-control", placeholder: "E-mail", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, autocomplete: "off", class:"form-control", placeholder: "Password  (6 characters minimum) ", autofocus: true  %>
      </div>

      <div class="form-group">
        <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control", placeholder: "Password Confirmation", autofocus: true  %>
      </div>

      <div class="submit align-center">
  			<br>
  			<button type="submit" class="btn btn-d btn-round btn-sm">Sign Up</button>
  		</div>

      <% end %>
      <br>
      <div class="font-inc align-center">
        <%= link_to "Login", login_path, :class => 'navbar-link'  %>
      </div>


    </div>
  </div>

</section>

app/views/users/show.html.erb
<section class="module">
  <div class="container">
    <div class="col-sm-3 col-md-6 col-lg-12 main">
      <h1 class="page-header font-alt"><%= current_user.username %>'s Inbox </h1>
      <div class="table-responsive">
        <table class="table table-striped font-inc">
          <thead>
            <tr>
              <th>Chats</th>
              <th>Remove</th>
            </tr>
          </thead>
          <tbody>
              <div class="item font-alt">
                <% @chats.each do |chat| %>
                  <% if chat.sender_id == current_user.id || chat.receiver_id == current_user.id %>
                    <% if chat.sender_id == current_user.id %>
                      <% receiver = User.find(chat.receiver_id) %>
                    <% else %>
                      <% receiver = User.find(chat.sender_id) %>
                    <% end %>
                    <tr>
                      <td><%= link_to receiver.first_name, chat_messages_path(chat)%></td>
                      <td><%= link_to "Delete", chat_path(chat), remote: true, method: :delete%></td>
                    </tr>
                  <% end %>
                <% end %>
              </div>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</div>

</section>

app/views/welcome/index.html.erb
<section class="module">
  <div class="container">
    <div class="row">

      <div class="col-sm-6 col-sm-offset-3">

        <h2 class="module-title align-center font-alt" id="welcome">Welcome to ActionCable Messenger</h2>

        <div class="module-subtitle align-center font-inc">
          By Cindy Kim
        </div>

      </div>

    </div>
  </div>
</section>